// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCAljPeoMmBy64wvk1epcaZ7L5rSj4Jok',
    appId: '1:321607552418:android:b5d86d3273e0d3b134b6fb',
    messagingSenderId: '321607552418',
    projectId: 'fluttershop-22ec2',
    storageBucket: 'fluttershop-22ec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwH4r6RJuyjRlgt4aFdNh6NfEObkJVu38',
    appId: '1:321607552418:ios:5df8a3d58bedcf8034b6fb',
    messagingSenderId: '321607552418',
    projectId: 'fluttershop-22ec2',
    storageBucket: 'fluttershop-22ec2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwH4r6RJuyjRlgt4aFdNh6NfEObkJVu38',
    appId: '1:321607552418:ios:5df8a3d58bedcf8034b6fb',
    messagingSenderId: '321607552418',
    projectId: 'fluttershop-22ec2',
    storageBucket: 'fluttershop-22ec2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAam1sg0DZavScR22lpnjP6-AkDTW9nq5I',
    appId: '1:321607552418:web:919abf6c219b74f234b6fb',
    messagingSenderId: '321607552418',
    projectId: 'fluttershop-22ec2',
    authDomain: 'fluttershop-22ec2.firebaseapp.com',
    storageBucket: 'fluttershop-22ec2.firebasestorage.app',
    measurementId: 'G-5FZHZYH2SN',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAam1sg0DZavScR22lpnjP6-AkDTW9nq5I',
    appId: '1:321607552418:web:f0b970d8cc08c33c34b6fb',
    messagingSenderId: '321607552418',
    projectId: 'fluttershop-22ec2',
    authDomain: 'fluttershop-22ec2.firebaseapp.com',
    storageBucket: 'fluttershop-22ec2.firebasestorage.app',
    measurementId: 'G-WGKL8VE98C',
  );

}